### ISSUE TITLE
IOError: [Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by stroupjason** [HackerHouseYT/Tracking-Turret#4]
When trying to run python turret.py
```
Traceback (most recent call last):
  File "turret.py", line 411, in <module>
    t = Turret(friendly_mode=False)
  File "turret.py", line 177, in __init__
    self.mh = Adafruit_MotorHAT()
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_MotorHAT/Adafruit_MotorHAT_Motors.py", line 232, in __init__
    self._pwm = PWM(addr, debug=False, i2c=i2c, i2c_bus=i2c_bus)
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 59, in __init__
    self.setAllPWM(0, 0)
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 95, in setAllPWM
    self.i2c.write8(self.__ALL_LED_ON_L, on & 0xFF)
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_GPIO/I2C.py", line 114, in write8
    self._bus.write_byte_data(self._address, register, value)
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_PureIO/smbus.py", line 236, in write_byte_data
    self._device.write(data)
IOError: [Errno 121] Remote I/O error
```
I made sure I followed all of your instructions, via your GitHub README.md, but I still can't get this to work.  I did purchase a different motor hat model on accident: http://www.raspberrypiwiki.com/index.php/Stepper/Motor/Servo_Robot_Expansion_Board_SKU:418460. 

Do you have any recommendations?

**Comment by stroupjason** [comment]
UPDATE: I installed a new adafruit model P2348 stepper motor hat and still having the same issue. I ran a quick node script I created to fire off of pin #15 which is GPIO 22 and I am able to fire manually... I've tried everything. I hope I don't have a hardrive issue from the research I've done. I might try and wipe my sim card clean or buy a new  one and start all over again to make sure I've added an extra flag for my virtual env...  That's the only thing I can think of, which I'm almost 100% I did to gather the site-packages for the HAT and adding it to the specific env....HELP?

**Comment by stroupjason** [comment]
Hi all! Issue is resolved. When installing Adafruit I just needed to use --upgrade flag at the end:
```
sudo pip install git+https://github.com/adafruit/Adafruit-Motor-HAT-Python-Library
Collecting git+https://github.com/adafruit/Adafruit-Motor-HAT-Python-Library
  Cloning https://github.com/adafruit/Adafruit-Motor-HAT-Python-Library to /tmp/pip-QBJfQ2-build
  Requirement already satisfied (use --upgrade to upgrade): Adafruit-MotorHAT==1.4.0 from git+https://github.com/adafruit/Adafruit-Motor-HAT-Python-Library in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: Adafruit-GPIO>=0.7 in /usr/local/lib/python2.7/dist-packages (from Adafruit-MotorHAT==1.4.0)
Requirement already satisfied: adafruit-pureio in /usr/local/lib/python2.7/dist-packages (from Adafruit-GPIO>=0.7->Adafruit-MotorHAT==1.4.0)
Requirement already satisfied: spidev in /usr/lib/python2.7/dist-packages (from Adafruit-GPIO>=0.7->Adafruit-MotorHAT==1.4.0)
```
